#!/bin/sh -e
# vim: ft=sh

echo "Starting bootstrap"

echo "assume brew and yadm already installed, ssh keys already exist"

echo "1. Find homebrew"
_brew=$(which brew)
if [ $? != 0 ]; then
    echo "brew not in path"
    _brew="/opt/homebrew/bin/brew"
    ls $_brew
    if [ $? != 0]; then
        echo "ERROR: homebrew not installed"
        exit 1
    fi
fi
echo "homebrew is installed"

echo "2. Install Homebrew packages"
echo "this may require password"
$_brew bundle install

echo "4. Prepare tmux tpm"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
$HOME/.tmux/plugins/tpm/scripts/install_plugins.sh

echo "5. Install vim plugins"
vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'

echo "6. Update macOS settings"
echo "text edit open empty file by default"
defaults write com.apple.TextEdit NSShowAppCentricOpenPanelInsteadOfUntitledFile -bool false

echo "7. Login in Github"
echo "github and copilot itself"
gh auth login
echo "vim copilot"
vim '+Copilot setup'

echo 'done'
