vim.o.shiftwidth = 4 -- The number of spaces inserted for each indentation (default: 8)
vim.o.tabstop = 4 -- Insert n spaces for a tab (default: 8)
vim.o.softtabstop = 4 -- Number of spaces that a tab counts for while performing editing operations (default: 0)
vim.o.smartindent = true -- Make indenting smarter again (default: false)
vim.o.expandtab = true -- Convert tabs to spaces (default: false)
vim.o.autoindent = true -- Copy indent from current line when starting new one (default: true)
vim.o.breakindent = true -- Enable break indent (default: false)
