live_config_reload = true

import = [
    "~/.config/alacritty/monokai.toml",
    # "~/.config/alacritty/mondrian.toml",
    "~/.config/alacritty/victor-mono.toml",
    "~/.config/alacritty/keyboard.toml",
    "~/.config/alacritty/autostart.toml",
]

[font]
size = 14.0

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[scrolling]
history = 100000
multiplier = 0

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = true
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Fullscreen"

[window.padding]
x = 2
y = 0
