live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#75715e"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f8f8f2"
yellow = "#f4bf75"

[colors.cursor]
cursor = "#f8f8f2"
text = "#272822"

[colors.normal]
black = "#272822"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f8f8f2"
yellow = "#f4bf75"

[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[colors.selection]
background = "#3a3a3a"
foreground = "#ffffff"

[font]
size = 14.0

[font.bold]
family = "VictorMono Nerd Font"
style = "Light"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Medium Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "VictorMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 0


[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002\u0001"
key = "Tab"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002!"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002%"
key = "Key1"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u0002\""
key = "Key2"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u0002&"
key = "Key7"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u0002*"
key = "Key8"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u0002("
key = "Key9"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u0002)"
key = "Key0"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u0002["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002]"
key = "RBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u0005"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002H"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002J"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002K"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u0010"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002p"
key = "P"
mods = "Alt"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[scrolling]
history = 100000
multiplier = 0

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = true
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Fullscreen"

[window.padding]
x = 2
y = 0
