[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002\u0001"
key = "Tab"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002!"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Control"

# v split
# [[keyboard.bindings]]
# chars = "\u0002%"
# key = "Key1"
# mods = "Control|Alt"

# h split
# [[keyboard.bindings]]
# chars = "\u0002\""
# key = "Key2"
# mods = "Control|Alt"

# enter select mode
[[keyboard.bindings]]
chars = "\u0002["
key = "LBracket"
mods = "Alt"

# ?
[[keyboard.bindings]]
chars = "\u0002]"
key = "RBracket"
mods = "Alt"

# edit current buffer in vim
[[keyboard.bindings]]
chars = "\u0002\u0005"
key = "E"
mods = "Alt"

# Resize splits with Opt + HJKL
[[keyboard.bindings]]
chars = "\u0002H"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002J"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002K"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Alt"

# zoom
[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Alt"

# Run TMUX command - gping in a new window
[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Alt"

# switch to prev window
[[keyboard.bindings]]
chars = "\u0002p"
key = "P"
mods = "Alt"

# rename window
[[keyboard.bindings]]
chars = "\u0002\u002c"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u002c"
key = "'"
mods = "Alt"

# Split TMUX with Opt + Shift + HJKL
[[keyboard.bindings]]
chars = "\u0002V"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002s"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002S"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002v"
key = "L"
mods = "Alt|Shift"

# Split TMUX with Opt + Ctrl + HJKL
[[keyboard.bindings]]
chars = "\u0002V"
key = "H"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u0002s"
key = "J"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u0002S"
key = "K"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u0002v"
key = "L"
mods = "Alt|Control"

# unbind default
# https://alacritty.org/config-alacritty-bindings.html
[[keyboard.bindings]]
action = "None"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "T"
mods = "Command"

# allow to create a new window with septaccord
[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command|Control|Alt|Shift"
