[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[colors.cursor]
cursor = "#f8f8f2"
text = "#272822"

[colors.selection]
background = "#3a3a3a"
foreground = "#ffffff"

[colors.bright]
black = "#75715e"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f8f8f2"
yellow = "#f4bf75"

[colors.normal]
black = "#272822"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f8f8f2"
yellow = "#f4bf75"

