[font.bold]
family = "VictorMono Nerd Font"
style = "Light"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Medium Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "VictorMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 0

