[font.bold]
family = "VictorMono Nerd Font"
# style = "SemiBold"
style = "Regular"

[font.bold_italic]
family = "VictorMono Nerd Font"
# style = "Medium"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "VictorMono Nerd Font"
style = "Regular"

[font.normal]
family = "VictorMono Nerd Font"
# style = "Bold"
# style = "SemiBold"
# style = "Medium"
style = "Regular"
# style = "Light"

[font.offset]
x = 0
y = 0

