[font.bold]
family = "VictorMono Nerd Font"
style = "Light"
# style = "ExtraLight"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Medium Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "VictorMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "VictorMono Nerd Font"
# style = "Medium"
style = "Regular"
# style = "Light"
# style = "ExtraLight"

[font.offset]
x = 0
y = 0

